apiVersion: v1
data:
  redis.conf: |-
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_I
P}/" ${REDIS_NODES}
    exec "$@"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"redis.conf":"cluster-enabled yes\ncluster-require-full
-coverage no\ncluster-node-timeout 15000\ncluster-config-file /data/nodes.conf\ncluster-migration-barrier 1\nappendonly yes\nprotected-mode no","update-node.sh":"#!/bin/sh\nREDIS_NODES=\"/data/nodes.conf\"\nsed -i -e \"/myself/ s/[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}/${POD_IP}/\" ${REDIS_NODES}\nexec \"$@\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2020-09-11T06:28:24Z","name":"redis-cluster-configmap","namespace":"default","resourceVersion":"29967","selfLink":"/api/v1/namespaces/default/configmaps/redis-cluster-configmap","uid":"fec2b917-f3f7-11ea-9dfb-0242ac11003d"}}
  creationTimestamp: "2021-01-09T19:32:47Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:redis.conf: {}
        f:update-node.sh: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-01-09T19:32:47Z"
  name: redis-cluster-configmap
  namespace: default
  resourceVersion: "584"
  selfLink: /api/v1/namespaces/default/configmaps/redis-cluster-configmap
  uid: 5faeafc0-954a-48c5-aea9-a651e47f5abb
